### PR TITLE
Change Translate to class

### PR DESCRIPTION
**Pull request by wannaphong**
from #439 , I change `pythainlp.translate.translate` function to `pythainlp.translate.Translate` class and I update docs.

### CODE REVIEW

**Comment by wannaphong** [comment]
Google colab for test https://colab.research.google.com/drive/1tTNIj996ySPdTPuKoXo976Gd6Du-cDIE?usp=sharing

**Comment by bact** [comment]
What about split the class to two classes?
One for EN->TH, another for TH->EN ?
This way, the user will load only the model that they will use to the memory?

Let me try that.

**Comment by wannaphong** [comment]
OK

**Review by bact — APPROVED** [review]
Looks good.

**Pull request merged**
