### PR TITLE
Add correct engine

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes

Add more spelling engine

- Add [symspellpy ](https://github.com/mammothb/symspellpy)with unigram & bigram from TNC - symspellpy is a Python port of SymSpell v6.5.
- Add [Phunspell](https://github.com/dvwright/phunspell) - A pure Python spell checker utilizing spylls a port of Hunspell.
- Add spell_sent & correct_sent function

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
`phunspell` is not working with python 3.6.

**Comment by wannaphong** [comment]
Colab for testing: https://colab.research.google.com/drive/1xgp_txclvolD7O913znqiBjD_7GdtAOM?usp=sharing

**Comment by bact** [comment]
> python 3.6.

Python 3.6 EOL is 2021-12-23, only months away from now.
Maybe have to consider if the next version of PyThaiNLP will going to support 3.6 after its EOL or not.

**Comment by wannaphong** [comment]
> 
> 
> > python 3.6.
> 
> Python 3.6 EOL is 2021-12-23, only months away from now.
> Maybe have to consider if the next version of PyThaiNLP will going to support 3.6 after its EOL or not.

End of support for Python 3.6 in the next version of PyThaiNLP #592

**Pull request merged**
