### PR TITLE
Support installing PyThaiNLP with tensorflow-gpu

### PR DESCRIPTION
**Pull request by cwt**
Background: I'm developing/learning Thai NLP on NVIDIA Jetson Nano, which it has _only_ **tensorflow-gpu** package (no generic tensorflow).

To be able to install PyThaiNLP with _deepcut_ or _full_ extra on this platform, I added 2 extras; `deepcut_gpu` and `full_gpu` that require `tensorflow-gpu` instead of `tensorflow`.

Please note that there are also many things that needed to be prepared or fixed before you can run `pip install pythainlp[full_gpu]`, which I explained a little bit about them in my [microblog](https://c3po.bashell.com/note/fe494ce7797a0c71).

### CODE REVIEW

**Comment by heytitle** [comment]
Hi,

Thanks for the PR. I've recently tested running DeepCut on GPU. I found that DeepCut's speed is actually slower than using CPU. This is quite strange. Please see https://github.com/rkcosmos/deepcut/issues/53 for further details.

It  would be good if you can confirm that DeepCut indeed uses GPU while running. For example, you might open `nvidia-smi` while executing your script.

**Comment by cwt** [comment]
@heytitle Hi, it's not about the speed but for **NVIDIA Jetson Nano** there is only tensorflow-gpu available. We can't install generic tensorflow, that is why I create this PR.

for more information please see the link: https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html

also quoted from [NVIDIA support](https://devtalk.nvidia.com/default/topic/1055327/jetson-nano/gpu-usage-info-nvidia-smi-is-not-there-/):
> nvidia-smi isn't supported on Tegra-based platforms.

**Comment by heytitle** [comment]
IC. I'm wondering whether we should fix the dependencies here or in DeepCut.

@wannaphongcom  what do you think?

**Comment by bact** [comment]
I suggest that we should remove deepcut in the next version of pythainlp.
People want to use it can install it easily with pip anyway. This will makes pythainlp smaller and easier to maintain as well.

**Comment by bact** [comment]
> IC. I'm wondering whether we should fix the dependencies here or in DeepCut.
> 
> @wannaphongcom what do you think?

I suggest that we should remove deepcut in the next version of pythainlp.
People want to use it can install it easily with pip anyway. This will makes pythainlp smaller and easier to maintain as well.

**Comment by cstorm125** [comment]
Agreed with removing DeepCut since functionality-wise AttaCut is an acceptable replacement for almost all use cases. We are also moving to pure Pytorch in subsequent versions.

**Comment by bact** [comment]
As we will remove tensorflow from our dependencies, this will no longer an issue.

See https://github.com/PyThaiNLP/pythainlp/pull/283

**Comment by bact** [comment]
Close, as no longer an issue after PR #283 is merged.

**Pull request closed without merging**
