### PR TITLE
Add clause_tokenize warnings

### PR DESCRIPTION
**Pull request by wannaphong**
Add clause_tokenize warnings from #1024

### CODE REVIEW

**Comment by bact** [comment]
Build failed. Something to do with fairseq

**Comment by wannaphong** [comment]
> Build failed. Something to do with fairseq

It uses old unit test.

**Comment by bact** [comment]
Any reason why don't we apply this change directly to 5.0.5?

**Comment by bact** [comment]
Oh. Ok. Got it. This is going to be 5.0.5, right?

**Review by bact — APPROVED** [review]

**Comment by wannaphong** [comment]
> Oh. Ok. Got it. This is going to be 5.0.5, right?

You right.

**Pull request merged**
