### PR TITLE
Tokenize repeating dots and commas from numbers (fix #461)

### LINKED ISSUE #461: Problem with syllable tokenization
**Describe the bug**
I've observed a behavior that is worth being discussed here. In short, when there are some punctuations, syllable tokenizes would return some incorrect syllables, both from the default engine and `ssg`.

image

**To Reproduce**
Please see: https://colab.research.google.com/drive/12gxSmskjHCQzqV1-Nb4IOaBD-LJ0ARl5?usp=sharing

**Expected behavior**
imho, the expected result is `['หน้า', 'ที่', ' ', '19', '...'] `. To achieve this, we can split the sentence by punctuation first then do syllable tokenization for each part.

What do you think?

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes
I change a rule of `_RE_NONTHAI` in `newmm` and `multi_cut`.

ภาพ

### How this fixes it

Add rule of float number and number.

Fixes #461

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
Colab: https://colab.research.google.com/drive/1OcC7mCwAQQvx7qC9o6DdXcre7V4ohCtp?usp=sharing

**Review by bact — CHANGES_REQUESTED** [review]
Nice work. Can we add test cases for this?

May be something like:
- "19..." -> ['19', '...']
- "19." -> ['19', '.']
- "19.84" -> ['19.84']
- "127.0.0.1" -> ['127.0.0.1']
- "USD1,984.42" -> ['USD', '1,984.42']

**Comment by wannaphong** [comment]
> 
> 
> Nice work. Can we add test cases for this?
> 
> May be something like:
> 
>     * "19..." -> ['19', '...']
> 
>     * "19." -> ['19', '.']
> 
>     * "19.84" -> ['19.84']
> 
>     * "127.0.0.1" -> ['127.0.0.1']
> 
>     * "USD1,984.42" -> ['USD', '1,984.42']

OK

**Comment by bact** [comment]
I think the code and the test cases themselves are good (thanks), but the problem is around coverall for macOS hmm..

**Review by bact — APPROVED** [review]
The code and the test cases are good. Thank you.

**Pull request merged**
