### PR TITLE
Add crfcut v2 model

### PR DESCRIPTION
**Pull request by opalchonlapat**

### CODE REVIEW

**Review by cstorm125 — APPROVED** [review]
Approve changes in test cases because the new crfcut recognizes compound sentences better. Not ideal but this is the best we can do before we can have real linguistic guidelines.

**Comment by p16i** [comment]
Should we remove the old model from `corpus`?

**Comment by cstorm125** [comment]
that's true @opalchonlapat can you help?

**Comment by bact** [comment]
See more about CRFCut in #337

**Pull request merged**
