### PR TITLE
Add pythainlp.augment

### LINKED ISSUE #578: Add Thai Text Augmentation
## Detailed description
Add Thai Text Augmentation to PyThaiNLP

## Context
Text Augmentation is tool for augmentation text. It is need for many nlp task. I think i may merge code from [ThaiTextAug](https://github.com/wannaphong/thaitextaug) to pythainlp.

## Possible implementation
It is need more requirements
- thai2transformers
- bpemb
- nltk

## Your environment
* PyThaiNLP version:
* Python version:
* Operating system and version (distro, 32/64-bit):
* More info (Docker, VM, etc.):

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes

Add Thai Text Augmentation #578

### How this fixes it

Description of how the changes fix the issue.

Fixes #578

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by bact** [comment]
To keep the name a bit consistent with others like pythainlp.tokenize, .translate, .transliterate, what about pythainlp.augment ?

**Comment by wannaphong** [comment]
> 
> 
> To keep the name a bit consistent with others like pythainlp.tokenize, .translate, .transliterate, what about pythainlp.augment ?

I agree. I will change it.

**Comment by wannaphong** [comment]
@bact I think it's ready.

**Comment by wannaphong** [comment]
> [Coverage Status](https://coveralls.io/builds/41439417)
> 
> Coverage decreased (-0.5%) to 95.541% when pulling **[c638e95](https://github.com/PyThaiNLP/pythainlp/commit/c638e9534c50fae26ba6377a297035fbca00747a) on add-textaugment** into **[ad20a1e](https://github.com/PyThaiNLP/pythainlp/commit/ad20a1e51674bb52378b383e950d30c1baa12a3b) on dev**.

Welcome back!

**Pull request merged**
