### PR TITLE
edited engine name and add phayathai pos_tag model to transformer_tag

### PR DESCRIPTION
**Pull request by MpolaarbearM**
### What does this changes

Add model lunarlist/pos_thai_phayathai to the pos tag transformer and fix some engine names being too long

### What was wrong

---
### How this fixes it

---
Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

### CODE REVIEW

**Comment by bact** [comment]
Tag @pavaris-pm as they just made related changes in #865 and may have few comments.

**Comment by pavaris-pm** [comment]
@MpolaarbearM I'm not sure about this. Did you sync the change from the upstream repo to your forked version repo before made this PR? since I've a discussion about model name / code refactoring with @bact and made change by adding dictionary lookup in PR #865, but seems like the change you've made in this PR did not match with the previous version that I do code refactorization krub.

**Comment by pavaris-pm** [comment]
> @MpolaarbearM I'm not sure about this. Did you sync the change from the upstream repo to your forked version repo before made this PR? since I've a discussion about model name / code refactoring with @bact and made change by adding dictionary lookup in PR #865, but seems like the change you've made in this PR did not match with the previous version that I do code refactorization krub.

@MpolaarbearM  i already fix it already by sync the change in new PR #873 . You can now close this PR after saw this comment krub. 

However, big thanks for your effort for training the pos tagging model on blackboard corpus. I promise that i will not forget to make a `co-authored commit` to give you a credit for it as well. According to that, can you give me an email that you currently use with your github ?, so that i can make a co-authored commit for you krub. if you do not want to show your email here, you can send it via my email as shown in my github profile krub.

**Comment by MpolaarbearM** [comment]
@pavaris-pm thank you very much krub!

**Pull request closed without merging**
