### PR TITLE
Add tokenization-benchmark to PyThaiNLP

### PR DESCRIPTION
**Pull request by wannaphongcom**
Co-Authored-By: Pattarawat Chormai <heytitle@users.noreply.github.com>

### CODE REVIEW

**Comment by heytitle** [comment]
@wannaphongcom  how should I fix the styling issues? 

Do you think it's better to keep the module separately? I have a second thought that keeping the module separately would allow us to release it easily.

I could imagine cases that we might need to fix bugs in the benchmark scripts. Usually, this kind of bugs are quite urgent.

**Comment by wannaphongcom** [comment]
@heytitle You can fix the styling (Read [PEP8](https://www.python.org/dev/peps/pep-0008/)) or use [autopep8](https://pypi.org/project/autopep8/).

We don't need to follow all pep8speaks.

**Comment by heytitle** [comment]
I mean where should I put the code. It seems all the code is inside this repository not the original one. 

So, should I clone this repo and push my fixes on this branch?

**Comment by wannaphongcom** [comment]
@heytitle Yes, you can. I want you to take care of this branch.

**Comment by heytitle** [comment]
@wannaphongcom 

I've solved almost all issues. Could you please take a look again and see whether it's mergeable.

**Comment by wannaphongcom** [comment]
@heytitle  It's ok.

**Comment by wannaphongcom** [comment]
- [ ] Add Document
- [ ] Add type hints

**Comment by wannaphongcom** [comment]
Document

Document

**Comment by wannaphongcom** [comment]
Now, Can i merge this pull request also?

**Comment by heytitle** [comment]
Hi, 

I would like to add some stuff. I'll ping you when it's ready.

**Comment by heytitle** [comment]
This illustration was added to the document.
Screenshot 2019-08-21 01 10 15


@wannaphongcom i'm happy with the document now.  Please proceed the PR further.  🍺

**Comment by wannaphongcom** [comment]
@heytitle It's ok.  💯

**Pull request merged**
