### PR TITLE
Remove "ulmfit" engine option in word_tokenize()

### PR DESCRIPTION
**Pull request by bact**
"ulmfit" engine option is supposed to be used internally.
Remove to avoid confusion.

See #222 for more discussion.

### CODE REVIEW

**Comment by cstorm125** [comment]
I suggest retaining the option to use frozen dict since `pythainlp.ulmfit` provides utility function to train ULMFit with fastai. If the name is really confusing maybe we can change to other more clear names?

**Comment by bact** [comment]
> I suggest retaining the option to use frozen dict since `pythainlp.ulmfit` provides utility function to train ULMFit with fastai. If the name is really confusing maybe we can change to other more clear names?

Does retaining the dictionary is already enough? Since the Tokenizer can be easily supplied with a custom dictionary now.

**Comment by cstorm125** [comment]
I see. Do you think it's better to implement such custom tokenizer in `pythainlp.ulmfit` or just show it in the tutorial notebooks?

**Comment by bact** [comment]
> I see. Do you think it's better to implement such custom tokenizer in `pythainlp.ulmfit` or just show it in the tutorial notebooks?

In the change I replace this:

```python
words = word_tokenize(text, engine="ulmfit")
```

with this:

```python
_pythainlp_tokenizer = Tokenizer(custom_dict=FROZEN_DICT_TRIE, engine="newmm")
words = _pythainlp_tokenizer.word_tokenize(text)
```
In terms of providing utility functions for fastai, I think this proposed changes will not break that. Every functions in `pythainlp.ulmfit` are still there.

We may also rename `FROZEN_DICT_TRIE` to `ULMFIT_DICT_TRIE` to make it more clear (the name "frozen dict" itself is not good as well though, may confused with Python's `frozenset()`). And maybe moved it from `pythainlp.tokenize` module to `pythainlp.ulmfit` module.

--

But if you think there can be a case that users may like to call `word_tokenize(text, engine="ulmfit")` by themselves, we may consider leave it as an option in `word_tokenize()`, just rename it to something less confused.

**Comment by cstorm125** [comment]
Ok understood. I'll merge this now.

**Pull request merged**
