### PR TITLE
Update sentenceseg_crfcut.model

### LINKED ISSUE #581: Retrained Model for PyThaiNLP 2.4
After #557 & #562, We needs to retrained all model in PyThaiNLP before we release PyThaiNLP 2.4 because dict & newmm has update.

**List model to retrained**

- [x] ThaiNER 1.5
- [x] CRFcut

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes

Retrained sentenceseg_crfcut.model for PyThaiNLP 2.4

### What was wrong

After #557 & #562, We needs to retrained all model in PyThaiNLP before we release PyThaiNLP 2.4 because dict & newmm has update.

### How this fixes it

Description of how the changes fix the issue.

Fixes #581

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
Log for retrained: https://github.com/PyThaiNLP/pythainlp_notebook/blob/master/sentenceseg_3dataset.ipynb

**Comment by wannaphong** [comment]
It is same f1-score.

**Comment by wannaphong** [comment]
before 4.32 MB after 3.9 MB ...

@cstorm125 @bact What are you think about it?

**Comment by bact** [comment]
> before 4.32 MB after 3.9 MB ...
> 
> @cstorm125 @bact What are you think about it?

Maybe related to the smaller vocab size?
words_th.txt is smaller in new version of PyThaiNLP after removing misspelled words.

Guessing.

**Comment by wannaphong** [comment]
> 
> 
> > before 4.32 MB after 3.9 MB ...
> > @cstorm125 @bact What are you think about it?
> 
> Maybe related to the smaller vocab size?
> words_th.txt is smaller in new version of PyThaiNLP after removing misspelled words.
> 
> Guessing.

Same.

**Pull request merged**
