### PR TITLE
Add misspell module

### LINKED ISSUE #549: Misspelling Model
## Detailed description
In most of practical settings, text often contains misspelling that could deteriorate NLP algorithms. To simulate such situations and evaluate how the problems could affect our algorithms, we need to simulate such misspelling. 

I propose to create a misspelling model based on neighborhood characters with respect to the standard Thai keyboard layout.    For example, consider `ก` we could replace it with `ห ำ พ ด ป แ` (illustrated  below).

image

For Thai characters that require to type with `Shift`, its neighbor characters are at the same buttons. For example, consider `ฏ`, its neighbor characters  are `ฆ ฎ ฑ โ )​ ฉ`

For a sentence, we can randomly select a character in a sentence and replaced it with its randomly selected neighborhood character as mentioned above.  For example, consider a sentence `นาย[ก]พูดไม่รู้เรื่อง` where we assume that `[_]` is the location we want to simulate a misspelling. These are possible misspelled versions that we can randomly select
```
นาย[ห]พูดไม่รู้เรื่อง
นาย[ำ]พูดไม่รู้เรื่อง
นาย[พ]พูดไม่รู้เรื่อง
นาย[ด]พูดไม่รู้เรื่อง
นาย[ป]พูดไม่รู้เรื่อง
นาย[แ]พูดไม่รู้เรื่อง
```

## Context
When we have this model, we could test how much these tasks are affected
- syllable and word tokenization
- part-of-speech tagging
- name entity recognition

## Possible implementation

My prototype can be found at https://colab.research.google.com/drive/1N3EeYyfTN8Qd8m5io6kzGqB5ndV6gA6J#scrollTo=ipeVmYz_0YcX.

### PR DESCRIPTION
**Pull request by p16i**
### What does this changes

This PR implements #549 

Note for self:
- To run the test:  `pytest  ./tests/test_misspell.py`
- implement an command line to produce a misspelled version of a file (line by line)
- using the command line to generate multiple files with different datasets and see how word segmentations performance are.

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
Do you wants hacktoberfest to this pull request?

**Review by wannaphong — CHANGES_REQUESTED** [review]
I think you may need to add docs to `pythainlp/mispell-generator/docs/api/tools.rst`.

`.. autofunction:: misspell`

**Comment by wannaphong** [comment]
All test of this PR are passed but some test are broke. I will fix it in dev branch.

**Comment by p16i** [comment]
Thanks for the suggestion @wannaphong!

> Do you wants hacktoberfest to this pull request?

I would let you and @bact decide whether the contribution of this PR is sufficient for the tag.

**Review by wannaphong — APPROVED** [review]

**Comment by wannaphong** [comment]
> 
> 
> Thanks for the suggestion @wannaphong!
> 
> > Do you wants hacktoberfest to this pull request?
> 
> I would let you and @bact decide whether the contribution of this PR is sufficient for the tag.

I approve and I think this PR is sufficient for the tag of hacktoberfest. and you? @bact

**Review by bact — APPROVED** [review]
LGTM

**Comment by p16i** [comment]
Perhaps, if this PR is ready, we can conclude and merge it. For the command line, we can implement it in a separate PR; its issue has been created (#615).

**Pull request merged**
