### PR TITLE
Feature/rust tokenizer

### PR DESCRIPTION
**Pull request by Gorlph**
### What does this changes

Add newmm word tokenization with default thai dictionary which is implemented in Rust.

### What was wrong

Word tokenization in python is quite slow for large text.

### How this fixes it

This rust module can speedup words tokenization process.

Fixes #...

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

### CODE REVIEW

**Comment by Gorlph** [comment]
Please try to build your own wheel for now. Contact me if you encounter problems with build process.

**Comment by cstorm125** [comment]
Great PR. Much needed as we work with larger and larger data like Assorted Thai Texts (@artificiala for visibility)

I did a benchmark vs old `newmm`. Sharing on Colab but need to run on local with instructions in this PR:
https://colab.research.google.com/drive/1mCeHRdj4TMzbIA4_xL2BY536v_5CYvFd?usp=sharing

In short, it is 2 times faster on average (on `wisesight_sentiment` sequences) and will be exponentially faster with sequence length 1,000 words and above.

**Comment by bact** [comment]
Cool. Actually this can be an independent module in itself and I would suggest to do so as it will help people who just want to have the tokenizer to avoid the whole unnecessary dependencies.

Python-binding in oxidized_thainlp/__init__.py is probably the only main thing to be added to the Python side of PyThaiNLP. The rest can be packaged independently and imported as a package to PyThaiNLP.

To make it an independent Rust module, you may like to have a separate copy of dictionary for the module. And in cargo.toml, just remove refs to pythainlp/corpus directory.

When being called as an independent Rust module, it will use its own dictionary; but when being called through the Python-binding, the load_dict() on the Python side can decide which dictionary to use (and this can be one in pythainlp/corpus).

That's my thought, seeing potential of this contribution. Thanks again for this.

**Comment by bact** [comment]
Move to https://github.com/PyThaiNLP/oxidized-thainlp/

**Pull request closed without merging**
