### PR TITLE
Pin h5py to < 3 to avoid breaks in Keras in Tensorflow 2.3.1 + Update test config

### PR DESCRIPTION
**Pull request by bact**
- Pin h5py to >=2.10.0,<3 to avoid breaks with Keras 2.3.1 See https://github.com/tensorflow/tensorflow/issues/44467
- Update lib versions in test config

### CODE REVIEW

**Comment by wannaphong** [comment]
I think we don't have to add keras to `requirements.txt` because Deepcut used `tensorflow.keras` not `keras`.

**Comment by bact** [comment]
> I think we don't have to add keras to `requirements.txt` because Deepcut used `tensorflow.keras` not `keras`.

Thanks. Fixed.

**Comment by wannaphong** [comment]
Add "`env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`" to `/.github/workflows/pythainlp-test.yml`.

**Comment by wannaphong** [comment]
All test passed but coveralls is break.

**Comment by bact** [comment]
> All test passed but coveralls is break.

All passed now. Thanks.

**Pull request merged**
