### PR TITLE
Refactor util package as well as improve performance

### PR DESCRIPTION
**Pull request by Peradon**
- I move some of the constant variables, which are declared inside the function, out as global variables. this will improve the speed required to execute each of the function.
- refactor deletetone function to be a snake case.

### CODE REVIEW

**Comment by bact** [comment]
>     * I move some of the constant variables, which are declared inside the function, out as global variables. this will improve the speed required to execute each of the function.
> 
>     * refactor deletetone function to be a snake case.

Thanks for the refactoring. I further refactor the code to reduce the call stack. You may like to review the code.

Btw, the function name `thaicheck()` is not that meaninful. Any suggestion?

@wannaphongcom @korakot any idea?

Should we call it `is_authentic_thai()` or something similar?
(and we can have `thaicheck()` as an alias to keep code compatability, and deprecate it later)

**Comment by wannaphongcom** [comment]
@bact "คำไทยแท้" is authentic thai word or real thai word?

**Comment by wannaphongcom** [comment]
I do not know what to call it.

**Comment by Peradon** [comment]
> @bact "คำไทยแท้" is authentic thai word or real thai word?

Or we can go with "is_original_thai"?

**Comment by bact** [comment]
I think we have a much simpler code now. Thanks to @Peradon.

Test coverage drops because the functions `deletetone()` and `thaicheck()` to maintain compatibility. These will be eventually ok after we remove the functions later in the future. (Or we can even include them in the test, if we like).

Should we merge?

**Comment by Peradon** [comment]
@bact I just noticed that you were my professor on Computer Ethics and Laws at SE, KMITL. nice to meet you again krub.

**Comment by bact** [comment]
There's another option: `is_native_thai()`

**Comment by bact** [comment]
I think it's good enough now. If there's anything, open new PR.

**Pull request merged**
