### PR TITLE
Improve: Reduce import time

### PR DESCRIPTION
**Pull request by wannaphong**
Improve: reduce import time

### CODE REVIEW

**Comment by wannaphong** [comment]
**PyThaiNLP v3.1.0**
> python -X importtime -c "from pythainlp.tokenize import word_tokenize" 2> wordcut-3.1.log

ภาพ

**This patch**

> python -X importtime -c "from pythainlp.tokenize import word_tokenize" 2> wordcut-import2.log

ภาพ

**Comment by wannaphong** [comment]
[wordcut-3.1.log](https://github.com/PyThaiNLP/pythainlp/files/9739656/wordcut-3.1.log)
[wordcut-import2.log](https://github.com/PyThaiNLP/pythainlp/files/9739657/wordcut-import2.log)

**Comment by BLKSerene** [comment]
Well, delaying imports of optional dependencies of `PyThaiNLP`, like `sentencepiece`, `pycrfsuite`, and `gensim`, is fine (except `Requests`, which is a required dependency), but I think that delaying import statements of Python standard libraries, such as `random`, `tarfile`, and `shutil`, would make future maintenance work trickier, and would not impact much on the import speed?

**Comment by wannaphong** [comment]
> Well, delaying imports of optional dependencies of `PyThaiNLP`, like `sentencepiece`, `pycrfsuite`, and `gensim`, is fine (except `Requests`, which is a required dependency), but I think that delaying import statements of Python standard libraries, such as `random`, `tarfile`, and `shutil`, would make future maintenance work trickier, and would not impact much on the import speed?

I think it isn't impact the future maintenance because It uses only few function and use few time (train Perceptron model, download file, unzip file).

**Pull request merged**
