### PR TITLE
[WIP] Add BEST I corpus reader

### PR DESCRIPTION
**Pull request by wannaphong**
I wrote a the BEST I corpus reader. It's can read BEST I corpus. It's return list words or `CoNLL` for NER.

BEST I Corpus : [nectec.or.th/corpus/index.php?league=pm](https://www.nectec.or.th/corpus/index.php?league=pm)

**TODO**

- [X] Add Test

- [ ]  Add docs

### CODE REVIEW

**Comment by p16i** [comment]
How would you bypass the login? I thought about doing this but I'm not sure how I should overcome the login.

Is it possible to download and host the data else where? 

I've seen a couple of framework doing something similar. When you download a dataset with license, the framework automatically will prompt a dialog for the consent to the data's license. 

@bact  any suggestion on this?

**Comment by bact** [comment]
> How would you bypass the login? I thought about doing this but I'm not sure how I should overcome the login.
> 
> Is it possible to download and host the data else where?
> 
> I've seen a couple of framework doing something similar. When you download a dataset with license, the framework automatically will prompt a dialog for the consent to the data's license.
> 
> @bact any suggestion on this?

We can do that as well.

This is something that may related #385 .

I'm still thinking. This is what I currently have in mind, still not certain:

- For the installation of external dataset (does not come from PyThaiNLP project and need additional user acceptance of a license agreement) -- we should have either an interactive prompt or a configuration file that state the acceptance for each of the datasets that the user wishes to use
  - At the point of installation, a configuration file will be consulted. If an acceptance is found, the dataset will get install without prompt.
  - If the acceptance in the config file is not found, a prompt maybe shown. -- But this a use case without human attention should also be thinking about as well. In that case, we should raise an exception or an exit error code should be returned.

- For the installation of any dataset that is from PyThaiNLP project. We may install it without prompt. Taken that the license agreement acceptance has been made already when the user download and install PyThaiNLP.

**Comment by p16i** [comment]
I think prompting is quite intuitive. If the user says yes, we can also create a file with their agreement answer.  If this file already exists, the prompt can be bypassed, e.g. the user can manually creates the file as well.

**Comment by p16i** [comment]
One quick question: should we implement this functionality in this main repo?
It seems to me that having a separate repo might be better in term of releasing.

**Comment by wannaphong** [comment]
> 
> 
> One quick question: should we implement this functionality in this main repo?
> It seems to me that having a separate repo might be better in term of releasing.

I agree. It might be better in term of both release and management.

**Comment by p16i** [comment]
I've actually tried to implement something similar but also including government API wrappers. Here is the project.

https://github.com/codeforthailand/databuri

I can transfer it to pythainlp. We might consider remove the API wrappers and implement only the dataset related stuff. 

What do you think? I actually like the name. So, that is why I mention it here. We can also do everything from scratch. 

@bact @wannaphong  what do you think?

**Comment by wannaphong** [comment]
> 
> 
> I've actually tried to implement something similar but also including government API wrappers. Here is the project.
> 
> https://github.com/codeforthailand/databuri
> 
> I can transfer it to pythainlp. We might consider remove the API wrappers and implement only the dataset related stuff.
> 
> What do you think? I actually like the name. So, that is why I mention it here. We can also do everything from scratch.
> 
> @bact @wannaphong what do you think?

This project is very interesting. I think we can continue to develop this project.

@bact @cstorm125 @korakot  what do you think?

**Comment by bact** [comment]
One difference is one is accessing data from the network (internet is required) and another get it from a local file.

The nature of the data is probably different as well. One is more structured? Another is more like text?

I think in general it's good to provide some library to make it easier to get access to the data, to increase to use of the existing data. But not sure yet about the design.

**Comment by cstorm125** [comment]
Adding BEST for word tokenization to huggingface/datasets https://github.com/huggingface/datasets/pull/1385

**Comment by wannaphong** [comment]
> 
> 
> Adding BEST for word tokenization to huggingface/datasets [huggingface/datasets#1385](https://github.com/huggingface/datasets/pull/1385)

I thinks i will close this pull request because you could use [🤗Datasets](https://github.com/huggingface/datasets) for read thai corpus.

**Comment by cstorm125** [comment]
> > Adding BEST for word tokenization to huggingface/datasets [huggingface/datasets#1385](https://github.com/huggingface/datasets/pull/1385)
> 
> I thinks i will close this pull request because you could use [🤗Datasets](https://github.com/huggingface/datasets) for read thai corpus.

[🤗Datasets](https://github.com/huggingface/datasets) is a new hope for big success for Thai NLP.

**Pull request closed without merging**
