### PR TITLE
[WIP] Add GPT-Neo Few-Shot Learning

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes

Add GPT-Neo Few-Shot Learning

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [ ] Passed code styles and structures
- [ ] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
Google colab for testing: https://drive.google.com/file/d/1kSqU2YwoCBnJv3Kej5eRHNtHnZLsRIvW/view?usp=sharing
ภาพ

**Comment by wannaphong** [comment]
Wait for future

**Comment by p16i** [comment]
Would you mind listing the functionalities of this new algorithm?
Perhaps, it might also be useful to indicate which functionalities already exist in PyThaiNLP and which one are not.

**Comment by wannaphong** [comment]
> 
> 
> Would you mind listing the functionalities of this new algorithm?
> Perhaps, it might also be useful to indicate which functionalities already exist in PyThaiNLP and which one are not.

This class is few-shot learning. It can built text classification or chatbot or text2sql from small data and It train few-shot step. It can using for many task ex education, chatbot and other. Now, I am training fine-tune GPT-Neo-125M for thai language. Soon

**Pull request closed without merging**
