### PR TITLE
pythainlp.spell: Fix type annotations, docstring spellings, etc.

### PR DESCRIPTION
**Pull request by abhabongse**
Three main improvements:
1. Fixed some mismatched type annotations in the original code
2. Corrected the spelling, ironically, of some words in this subpackage. (I also took some liberty of modifying some docstrings to make it clearer.)
3. Rewrote some lines of Python code that could obviously be improved or corrected.

Please review.

### CODE REVIEW

**Comment by bact** [comment]
Thanks a lot. Lots of improvements.

One point: `_keep()` can also returns `dict_filter(word)` (apart from booleans), so I think we should keep the `Callable` part in return type.

**Comment by abhabongse** [comment]
About the `_keep()` function, since it returns the function application of `dict_filter: Callable[[str], bool]` with the input `word: str` (not the function itself), so I think overall `_keep()` will always return boolean?

**Comment by abhabongse** [comment]
Any suggestions to restrict the source file to 250 lines (according to codeclimate)?

**Comment by bact** [comment]
> About the `_keep()` function, since it returns the function application of `dict_filter: Callable[[str], bool]` with the input `word: str` (not the function itself), so I think overall `_keep()` will always return boolean?

True. Forgot that point.

**Comment by bact** [comment]
Thanks for additional tests and the proper return values for `spell()`

**Pull request merged**
