### PR TITLE
Add wangchanberta

### PR DESCRIPTION
**Pull request by wannaphong**
### What does this changes

I add ner from `wangchanberta` model.

GitHub: https://github.com/vistec-AI/thai2transformers

**How to used**
```python
from pythainlp.wangchanberta import ThaiNameTagger
ner = ThaiNameTagger(dataset_name = "thainer") # dataset_name: thainer or lst20
print(ner.get_ner("ทดสอบผมมีชื่อว่า นายวรรณพงษ์ ภัททิยไพบูลย์")) #[('ทดสอบผมมีชื่อว่า ', 'O'), ('นายวรรณพงษ์ ภัททิยไพบูลย์', 'PERSON')]
print(ner.get_ner("ทดสอบผมมีชื่อว่า นายวรรณพงษ์ ภัททิยไพบูลย์", tag=True)) #'ทดสอบผมมีชื่อว่า <PERSON>นายวรรณพงษ์ ภัททิยไพบูลย์</PERSON>'
```

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/PyThaiNLP/pythainlp/blob/dev/CONTRIBUTING.md) to this repository.

- [x] Passed code styles and structures
- [x] Passed code linting checks and unit test

### CODE REVIEW

**Comment by wannaphong** [comment]
Google colab notebook for test: https://colab.research.google.com/drive/1VfM7161u5ExKD6vFMDmxFTZf19EnrhgI?usp=sharing

**Review by cstorm125 — CHANGES_REQUESTED** [review]
Can you fix the behavior where it adds `_` in the beginning of sentence token? This is an artifact from when we train the model:

```
t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
>> ▁ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
```

I think it would be better for users if we return:

```
t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
>> ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
```

Also, I understand this is probably not best practice but the model tends to split entities like มหาลัย and จุฬา above (both labelled `B-ORG` by the model). Do you think it will be better if we merge `B-X, B-X` to `X` even though it is not `B-X, I-X`?

**Review by cstorm125 — COMMENTED** [review]
Should we allow `lst20` and `thainer` as choices?

**Comment by wannaphong** [comment]
> 
> 
> Should we allow `lst20` and `thainer` as choices?

Yes, It can choices `lst20` or `thainer`. `ThaiNameTagger(dataset_name="lst20")` or `ThaiNameTagger(dataset_name="thainer")`

**Comment by wannaphong** [comment]
> 
> 
> Can you fix the behavior where it adds `_` in the beginning of sentence token? This is an artifact from when we train the model:
> 
> ```
> t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
> >> ▁ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
> ```
> 
> I think it would be better for users if we return:
> 
> ```
> t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
> >> ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
> ```
> 
> Also, I understand this is probably not best practice but the model tends to split entities like มหาลัย and จุฬา above (both labelled `B-ORG` by the model). Do you think it will be better if we merge `B-X, B-X` to `X` even though it is not `B-X, I-X`?

Fixed.

**Comment by cstorm125** [comment]
> > Can you fix the behavior where it adds `_` in the beginning of sentence token? This is an artifact from when we train the model:
> > ```
> > t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
> > >> ▁ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
> > ```
> > 
> > 
> > I think it would be better for users if we return:
> > ```
> > t.get_ner("ผมกินข้าวที่มหาลัยจุฬา",tag=True)
> > >> ผมกินข้าวที่<ORGANIZATION>มหาลัย</ORGANIZATION><ORGANIZATION>จุฬา</ORGANIZATION>
> > ```
> > 
> > 
> > Also, I understand this is probably not best practice but the model tends to split entities like มหาลัย and จุฬา above (both labelled `B-ORG` by the model). Do you think it will be better if we merge `B-X, B-X` to `X` even though it is not `B-X, I-X`?
> 
> Fixed.

still returns
```
t.get_ner("โรงเรียนสวนกุหลาบเป็นโรงเรียนที่ดี แต่ไม่มีสวนกุหลาบ",tag=False)
>> [('', 'B-ORG'),
 ('โรงเรียน', 'B-ORG'),
 ('สวนกุหลาบ', 'B-ORG'),
 ('เป็น', 'O'),
 ('โรงเรียน', 'O'),
 ('ที่ดี', 'O'),
 (' ', 'O'),
 ('แต่ไม่มี', 'B-ORG'),
 ('สวนกุหลาบ', 'B-ORG')]
```

**Comment by p16i** [comment]
Before merging this PR, perhaps, it might be useful to compare the proposed and the equivalent existing ones in PyThaiNLP. 

According to [โมเดลประมวลผลภาษาไทยที่ใหญ่และก้าวหน้าที่สุดในขณะนี้ (Medium, 2020)][1], it seems `WangchanBERTa` significantly outperforms `CRF` only on ThaiNER-NER. Please correct me if I'm wrong, but I guess CRF is likely to be much smaller (and hence faster) than `WangchanBERTa`.

image


IMHO, doing this comparison would allow us to
- provide recommendations to the use on which method to use (in which situation)
- know what aspects we should improve upon.


[1]: https://medium.com/airesearch-in-th/wangchanberta-โมเดลประมวลผลภาษาไทยที่ใหญ่และก้าวหน้าที่สุดในขณะนี้-d920c27cd433

**Comment by cstorm125** [comment]
@wannaphong The issue for WangchanBERTa has been resolved in the [getting started notebook.](https://colab.research.google.com/drive/1Kbk6sBspZLwcnOE61adAQo30xxqOQ9ko?usp=sharing#scrollTo=XuzaarV7k4Ax) 
Can you make sure that your implementation gives the same results?

```
#using thainer dataset
โรงเรียนสวนกุหลาบเป็นโรงเรียนที่ดี แต่ไม่มีสวนกุหลาบ

[{'entity_group': 'ORGANIZATION', 'score': 0.782967746257782, 'word': ''},
 {'entity_group': 'ORGANIZATION',
  'score': 0.9278752207756042,
  'word': 'โรงเรียน'},
 {'entity_group': 'ORGANIZATION',
  'score': 0.9350618720054626,
  'word': 'สวนกุหลาบ'},
 {'entity_group': 'O',
  'score': 0.8276164361408779,
  'word': 'เป็นโรงเรียนที่ดี<_> แต่ไม่มีสวนกุหลาบ'}]
```

**Comment by cstorm125** [comment]
> Before merging this PR, perhaps, it might be useful to compare the proposed and the equivalent existing ones in PyThaiNLP.
> 
> According to [โมเดลประมวลผลภาษาไทยที่ใหญ่และก้าวหน้าที่สุดในขณะนี้ (Medium, 2020)](https://medium.com/airesearch-in-th/wangchanberta-%E0%B9%82%E0%B8%A1%E0%B9%80%E0%B8%94%E0%B8%A5%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A1%E0%B8%A7%E0%B8%A5%E0%B8%9C%E0%B8%A5%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%83%E0%B8%AB%E0%B8%8D%E0%B9%88%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%81%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%AA%E0%B8%B8%E0%B8%94%E0%B9%83%E0%B8%99%E0%B8%82%E0%B8%93%E0%B8%B0%E0%B8%99%E0%B8%B5%E0%B9%89-d920c27cd433), it seems `WangchanBERTa` significantly outperforms `CRF` only on ThaiNER-NER. Please correct me if I'm wrong, but I guess CRF is likely to be much smaller (and hence faster) than `WangchanBERTa`.
> 
> image
> 
> IMHO, doing this comparison would allow us to
> 
> * provide recommendations to the use on which method to use (in which situation)
> * know what aspects we should improve upon.

Agreed speed benchmark is a nice thing to have, although I would not mind merging without since users will have the choice to choose which modules (CRF or WangchanBERTa) when they use it anyways.

**Comment by wannaphong** [comment]
> 
> 
> @wannaphong The issue for WangchanBERTa has been resolved in the [getting started notebook.](https://colab.research.google.com/drive/1Kbk6sBspZLwcnOE61adAQo30xxqOQ9ko?usp=sharing#scrollTo=XuzaarV7k4Ax)
> Can you make sure that your implementation gives the same results?
> 
> ```
> #using thainer dataset
> โรงเรียนสวนกุหลาบเป็นโรงเรียนที่ดี แต่ไม่มีสวนกุหลาบ
> 
> [{'entity_group': 'ORGANIZATION', 'score': 0.782967746257782, 'word': ''},
>  {'entity_group': 'ORGANIZATION',
>   'score': 0.9278752207756042,
>   'word': 'โรงเรียน'},
>  {'entity_group': 'ORGANIZATION',
>   'score': 0.9350618720054626,
>   'word': 'สวนกุหลาบ'},
>  {'entity_group': 'O',
>   'score': 0.8276164361408779,
>   'word': 'เป็นโรงเรียนที่ดี<_> แต่ไม่มีสวนกุหลาบ'}]
> ```

Fixed

**Comment by cstorm125** [comment]
LGTM. You can add the speed benchmark @heytitle asked for later.

**Review by cstorm125 — APPROVED** [review]

**Comment by wannaphong** [comment]
> 
> 
> Before merging this PR, perhaps, it might be useful to compare the proposed and the equivalent existing ones in PyThaiNLP.
> 
> According to [โมเดลประมวลผลภาษาไทยที่ใหญ่และก้าวหน้าที่สุดในขณะนี้ (Medium, 2020)](https://medium.com/airesearch-in-th/wangchanberta-%E0%B9%82%E0%B8%A1%E0%B9%80%E0%B8%94%E0%B8%A5%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B8%A1%E0%B8%A7%E0%B8%A5%E0%B8%9C%E0%B8%A5%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%83%E0%B8%AB%E0%B8%8D%E0%B9%88%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%81%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%AA%E0%B8%B8%E0%B8%94%E0%B9%83%E0%B8%99%E0%B8%82%E0%B8%93%E0%B8%B0%E0%B8%99%E0%B8%B5%E0%B9%89-d920c27cd433), it seems `WangchanBERTa` significantly outperforms `CRF` only on ThaiNER-NER. Please correct me if I'm wrong, but I guess CRF is likely to be much smaller (and hence faster) than `WangchanBERTa`.
> 
> image
> 
> IMHO, doing this comparison would allow us to
> 
>     * provide recommendations to the use on which method to use (in which situation)
> 
>     * know what aspects we should improve upon.

I think that could be done later.

**Comment by wannaphong** [comment]
### Speed Benchmark

| Function                                                     | Named Entity Recognition | Part of Speech |
| ------------------------------------------------------------ | ------------------------ | -------------- |
| PyThaiNLP basic function (CRF for NER and perceptron model for POS) | 89.7 ms                  | 312 ms         |
| pythainlp.wangchanberta (CPU)                                | 9.64 s                   | 9.65 s         |
| pythainlp.wangchanberta (GPU)                                | 8.02 s                   | 8 s            |

Notebook:

- [PyThaiNLP basic function and pythainlp.wangchanberta CPU at Google Colab](https://colab.research.google.com/drive/1ymTVB1UESXAyZlSpjknCb72xpdcZ86Db?usp=sharing)
- [pythainlp.wangchanberta GPU](https://colab.research.google.com/drive/1AtkFT1HMGL2GO7O2tM_hi_7mExKwmhMw?usp=sharing)

**Comment by cstorm125** [comment]
> ### Speed Test
> Function	Named Entity Recognition	Part of Speech
> PyThaiNLP basic function (CRF for NER and perceptron model for POS)	89.7 ms	312 ms
> pythainlp.wangchanberta (CPU)	9.64 s	9.65 s
> pythainlp.wangchanberta (GPU)	8.02 s	8 s
> Notebook:
> 
> * [PyThaiNLP basic function and pythainlp.wangchanberta CPU at Google Colab](https://colab.research.google.com/drive/1ymTVB1UESXAyZlSpjknCb72xpdcZ86Db?usp=sharing)
> * [pythainlp.wangchanberta GPU](https://colab.research.google.com/drive/1AtkFT1HMGL2GO7O2tM_hi_7mExKwmhMw?usp=sharing)

LGTM

**Pull request merged**
