### PR TITLE
Move dill to pickle

### LINKED ISSUE #405: [DEP] Remove dill dependency
Currently, `pythainlp.tag.perceptron` is the only submodule that uses `dill`.

`dill` is an extended version of `pickle`.

Looks like we currently use a very basic functionality of of serialization that the standard `pickle` may able to handle and there's no need for `dill`.

https://github.com/PyThaiNLP/pythainlp/blob/d2b67e00a85c42212b668cb535dcfaaf010663e9/pythainlp/tag/perceptron.py#L19

Propose to investigate more and see if we can move from `dill` to `pickle` and reduce the number of mandatory dependencies by one.

### PR DESCRIPTION
**Pull request by wannaphong**
This pull request fixed #405

### CODE REVIEW

**Comment by bact** [comment]
Standard file extension for pickle is `.pkl`. May be renaming the files?

**Comment by bact** [comment]
Also remove dill from requirements.txt

**Comment by wannaphong** [comment]
> 
> 
> Also remove dill from requirements.txt

Done

**Comment by bact** [comment]
Does the tagger still working correctly / similar to when it was using dill?

Looks like at least it pass one test at https://github.com/PyThaiNLP/pythainlp/blob/a4bbac97958c1d00b379862118a4a38021a5753c/tests/test_tag.py#L49 

But just to confirm.

**Comment by wannaphong** [comment]
> 
> 
> Does the tagger still working correctly / similar to when it was using dill?
> 
> Looks like at least it pass one test at
> 
> https://github.com/PyThaiNLP/pythainlp/blob/a4bbac97958c1d00b379862118a4a38021a5753c/tests/test_tag.py#L49
> 
> But just to confirm.

It's working correctly.

**Pull request merged**
