### PR TITLE
Add mt5 cpe kmutt thai sentence sum

### PR DESCRIPTION
**Pull request by wannaphong**
Add mt5 cpe kmutt thai sentence sum

Model: https://huggingface.co/thanathorn/mt5-cpe-kmutt-thai-sentence-sum

### CODE REVIEW

**Comment by wannaphong** [comment]
@thanathornboss @thanathorn What do you think about this pull request?

**Comment by thanathorn** [comment]
@wannaphong  We are delighted to have our model merged with PyThaiNLP. We hope this integration could expand the potential and capabilities of PyThaiNLP!

**Comment by wannaphong** [comment]
> @wannaphong We are delighted to have our model merged with PyThaiNLP. We hope this integration could expand the potential and capabilities of PyThaiNLP!

Thank you!

**Comment by thanathornboss** [comment]
We are delighted to have our model merged with PyThaiNLP.

We hope this integration could expand the potential and capabilities of
PyThaiNLP!

**Pull request merged**
